FROM rocker/r-base

# install system dependencies (example)
#RUN apt-get update && apt-get install -y libxml2-dev

# install additional R packages (if needed)
#RUN R -e 'install.packages(c("package1", "package2"), repos = "https://cloud.r-project.org")'

# set working directory (optional)
# WORKDIR /app
